// Directus hook: d1-access-guard (ADR-0011)
//
// Row-level visibility (ADR-0011) is a set of Directus permission filters on the Lab Member policy.
// Four junction collections are part of those filters, so writing a row in one of them changes who
// can read a record:
//
//   sample_co_owners      a co-owner can read and edit the sample
//   project_investigators an investigator can read everything in the project
//   campaign_samples      a campaign's owner can read every sample in it
//   test_sessions_subject a trigger (migration 139) copies the test's first sample into
//                         test_sessions.sample_id, and the sample's owner and co-owners read and
//                         edit the test through it
//
// Directus does not apply item filters to *create* (and `validation` cannot reach across relations),
// so with the plain permissions any member could add themselves to a sample they cannot edit, to a
// project they do not lead, or add someone else's sample to their own campaign, and so read it. This
// hook closes that. It refuses a create (or an update that repoints a parent key) unless the caller
// may update the parent row: the sample for sample_co_owners, the project for project_investigators,
// the test for test_sessions_subject, and for campaign_samples BOTH the campaign and the sample.
//
// On update, only a parent key that changes is checked. A junction with several guards
// (campaign_samples) grants through the pair of keys, so when either key changes every guard is
// checked on the merged row ({...currentRow, ...payload}).
//
// The check is the parent's own update rule from scripts/access_rules.json, shipped as
// rules.json (generated by scripts/gen_access_rules.py; a drift check runs in CI and pre-commit), run
// through ItemsService with the caller's accountability, so nothing here restates the rules by hand.
//
// A second check closes a gap in the owner column. Several records may be updated by more people than
// may delete them (a sample: owner and co-owners update, only the owner deletes). Changing the owner
// column would hand delete to whoever changes it, so an update that changes it is refused unless the
// caller passes the record's DELETE rule, i.e. is its current owner. The owner may hand a record over;
// an editor may not take it. rules.json carries that rule as `ownerGuards`.
//
// Admins, and calls with no accountability (flows, scripts, other extensions), are not checked.
// Everyone else is, whatever their policy, because the rules are the Lab Member rules.
//
// Creating a parent and its junction rows in one request (a project with investigators, a sample with
// co-owners, a campaign with samples) is allowed. The parent has just been inserted, in the request's
// transaction, so its update rule may not hold for the creator (they named someone else as owner or
// PI), yet the creator is the one making that record. A parent key therefore also passes when the
// parent row was inserted by the current transaction (Postgres: its xmin is this transaction's id),
// without checking its update rule. Only a row INSERTED here and never updated since can match
// (xmin is this transaction AND the OCC version is still 1), so neither a row that merely exists nor
// a pre-existing row that was updated in this transaction (by this request, an FK action or a
// trigger) qualifies, and this never lets a member attach themselves to a record someone else made. The sample of
// a campaign_samples row is still checked (it is a different row) unless it is new too. A row
// created inside a savepoint carries the sub-transaction id and is not recognised: that fails closed
// (refused); Directus does not use savepoints.
// A payload that nests a brand-new parent (no key) is allowed: the caller is creating that record.

import { readFileSync } from 'node:fs';

const RULES = JSON.parse(readFileSync(new URL('./rules.json', import.meta.url), 'utf8'));
const GUARDS = RULES.guards;
const OWNER_GUARDS = RULES.ownerGuards ?? {};
const CURRENT_USER = '$CURRENT_USER';

// The shape of a Directus ForbiddenError (status 403, code FORBIDDEN), without importing the package.
function forbidden(reason) {
  const err = new Error(reason);
  err.name = 'DirectusError';
  err.status = 403;
  err.code = 'FORBIDDEN';
  err.extensions = { code: 'FORBIDDEN', reason };
  return err;
}

const isDenied = (err) => err?.code === 'FORBIDDEN' || err?.status === 403;
const isBlank = (value) => value === undefined || value === null || value === '';

// Replace $CURRENT_USER anywhere in a filter (ItemsService does not, only the REST layer does).
function substitute(node, user) {
  if (node === CURRENT_USER) return user;
  if (Array.isArray(node)) return node.map((item) => substitute(item, user));
  if (node && typeof node === 'object') {
    return Object.fromEntries(Object.entries(node).map(([key, value]) => [key, substitute(value, user)]));
  }
  return node;
}

// The parent key a payload names: a bare key, or the key inside a nested object. null = none given;
// undefined = a nested object with no key (a brand-new parent created in the same request).
function parentKey(value, key) {
  if (isBlank(value)) return null;
  if (typeof value !== 'object') return value;
  return isBlank(value[key]) ? undefined : value[key];
}

export default ({ filter }, { services }) => {
  const { ItemsService } = services;

  async function canUpdate(check, id, context) {
    const user = context.accountability.user;
    const svc = new ItemsService(check.parent, {
      knex: context.database,
      schema: context.schema,
      accountability: context.accountability,
    });
    try {
      const rows = await svc.readByQuery({
        fields: [check.key],
        filter: { _and: [{ [check.key]: { _eq: id } }, substitute(check.filter, user)] },
        limit: 1,
      });
      return rows.length > 0;
    } catch (err) {
      if (isDenied(err)) return false;
      throw err;
    }
  }

  // True when the parent row was INSERTED by the transaction this request runs in and not updated
  // since. xmin is the id of the transaction that last wrote the row (insert or update), and
  // pg_current_xact_id() is ours (cast to the 32-bit xid xmin uses), so xmin alone also matches a
  // pre-existing row merely UPDATED here (by this request, an FK action or a trigger side effect).
  // Every guarded parent (physical_samples, projects, campaigns, test_sessions) carries the OCC
  // `version` column, which starts at 1 and which occ_update_trigger_function() raises on every
  // update, so `version = 1` separates "inserted here, never updated" from "updated here". A parent
  // without that column would make this query fail, which refuses the write (fails closed); the
  // phase1 suite checks that all four have it and its trigger.
  async function createdInThisTransaction(check, id, context) {
    const row = await context
      .database(check.parent)
      .where(check.key, id)
      .whereRaw('xmin = pg_current_xact_id()::xid AND version = 1')
      .first(check.key);
    return row !== undefined && row !== null;
  }

  // Throws a 403 for the first parent the caller may not update. `fields` limits which of the
  // junction's parent keys are checked (the ones an update touches); null checks them all.
  async function enforce(collection, item, fields, context) {
    const checks = (GUARDS[collection] ?? []).filter((c) => !fields || fields.has(c.field));
    for (const check of checks) {
      const id = parentKey(item[check.field], check.key);
      if (id === null || id === undefined) continue; // not set (the database refuses it) or a new parent
      if (!(await canUpdate(check, id, context)) && !(await createdInThisTransaction(check, id, context))) {
        throw forbidden(
          `You can only change ${collection} rows for a ${check.parent} record you may update ` +
            `(you are not allowed to update ${check.parent} ${id}). This controls who can see the record (ADR-0011).`,
        );
      }
    }
  }

  const checked = (context) => context?.accountability?.user && context.accountability.admin !== true;
  const applies = (collection, context) => GUARDS[collection] !== undefined && checked(context);

  // Refuse an update that changes the owner column of a record the caller does not own.
  async function enforceOwner(collection, payload, keys, context) {
    const guard = OWNER_GUARDS[collection];
    // A value sent unchanged (an editor saving the whole form) is not a change. A nested object with
    // no key would create a new person, which is a change.
    const next = parentKey(payload[guard.field], guard.valueKey);
    const existing = await context.database(collection).whereIn(guard.key, keys).select(guard.key, guard.field);
    const current = new Map(existing.map((row) => [String(row[guard.key]), row[guard.field]]));
    for (const key of keys) {
      const known = current.has(String(key));
      const had = current.get(String(key));
      if (known && (isBlank(had) ? next === null : String(had) === String(next))) continue;
      if (!(await canUpdate({ parent: collection, key: guard.key, filter: guard.filter }, key, context))) {
        throw forbidden(
          `Only the owner of a ${collection} record can change who owns it (you do not own ${collection} ${key}). ` +
            'Whoever owns a record may delete it (ADR-0011).',
        );
      }
    }
  }

  filter('items.create', async (payload, meta, context) => {
    if (!applies(meta?.collection, context) || !payload) return payload;
    for (const item of Array.isArray(payload) ? payload : [payload]) {
      if (item && typeof item === 'object') await enforce(meta.collection, item, null, context);
    }
    return payload;
  });

  filter('items.update', async (payload, meta, context) => {
    const owned = OWNER_GUARDS[meta?.collection];
    if (owned && checked(context) && payload && typeof payload === 'object' && owned.field in payload) {
      const keys = Array.isArray(meta.keys) ? meta.keys.filter((key) => !isBlank(key)) : [];
      if (keys.length) await enforceOwner(meta.collection, payload, keys, context);
      return payload;
    }
    if (!applies(meta?.collection, context) || !payload || typeof payload !== 'object') return payload;
    // Only an update that repoints a parent key can grant anything; checking the new target is
    // enough, because the row's old parent was already allowed when it was written. A key sent
    // with its current value (an editor saving the whole form) is not a change.
    const collection = meta.collection;
    const guards = GUARDS[collection];
    const all = guards.map((c) => c.field);
    const touched = all.filter((f) => f in payload);
    if (touched.length === 0) return payload;
    const keys = Array.isArray(meta.keys) ? meta.keys : [];
    const pk = context.schema?.collections?.[collection]?.primary ?? 'id';
    const existing = keys.length ? await context.database(collection).whereIn(pk, keys).select(pk, ...all) : [];
    const rows = existing.length ? existing : [{}];
    const changed = new Set();
    for (const field of touched) {
      const next = parentKey(payload[field], guards.find((c) => c.field === field).key);
      if (next === null) continue; // clearing a parent key grants nothing (and the database refuses it)
      if (next === undefined || rows.some((row) => String(row[field]) !== String(next))) changed.add(field);
    }
    if (changed.size === 0) return payload;
    if (guards.length === 1) {
      await enforce(collection, payload, changed, context);
      return payload;
    }
    // A junction with several guards (campaign_samples) grants through the PAIR of keys, so moving
    // one key must still satisfy every guard: check the row as it will be after the update.
    for (const row of rows) await enforce(collection, { ...row, ...payload }, null, context);
    return payload;
  });
};
