-- migrate:up
-- Directus field metadata for the ④b per-method test fields. Conditional on
-- test_type so each method's panel appears only for that test. Idempotent: clears
-- any previously-inserted rows for these prefixes before re-inserting.

BEGIN;

DELETE FROM directus_fields WHERE collection='test_sessions' AND (field LIKE 'tribology\_%' OR field LIKE 'optical_microscopy\_%' OR field LIKE 'tem\_%' OR field LIKE 'alicona\_%' OR field LIKE 'clemx\_%' OR field LIKE 'dct\_%' OR field LIKE 'ct_scan\_%' OR field LIKE 'fatigue\_%' OR field LIKE 'creep\_%' OR field LIKE 'dma\_%');

-- ── tribology → test_sessions (inline, shows when test_type=tribology) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_test_standard', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 400, 'half', FALSE, '[{"language": "en-US", "translation": "Test Standard (e.g. ASTM G99)"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_configuration', NULL, 'select-dropdown', '{"choices": [{"text": "Pin-on-disc", "value": "pin_on_disc"}, {"text": "Ball-on-disc", "value": "ball_on_disc"}, {"text": "Reciprocating", "value": "reciprocating"}, {"text": "Block-on-ring", "value": "block_on_ring"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 401, 'half', FALSE, '[{"language": "en-US", "translation": "Configuration"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_counterface_material', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 402, 'half', FALSE, '[{"language": "en-US", "translation": "Counterface Material"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_normal_load_n', NULL, 'input', '{"step": 0.1, "suffix": "N"}', 'raw', NULL, FALSE, TRUE, 403, 'half', FALSE, '[{"language": "en-US", "translation": "Normal Load"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_sliding_speed_m_per_s', NULL, 'input', '{"step": 0.001, "suffix": "m/s"}', 'raw', NULL, FALSE, TRUE, 404, 'half', FALSE, '[{"language": "en-US", "translation": "Sliding Speed"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_sliding_distance_m', NULL, 'input', '{"step": 0.1, "suffix": "m"}', 'raw', NULL, FALSE, TRUE, 405, 'half', FALSE, '[{"language": "en-US", "translation": "Sliding Distance"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_lubrication', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 406, 'half', FALSE, '[{"language": "en-US", "translation": "Lubrication"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_test_temp_celsius', NULL, 'input', '{"step": 0.1, "suffix": "\u00b0C"}', 'raw', NULL, FALSE, TRUE, 407, 'half', FALSE, '[{"language": "en-US", "translation": "Test Temperature"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_coefficient_of_friction', NULL, 'input', '{"step": 0.0001}', 'raw', NULL, FALSE, TRUE, 408, 'half', FALSE, '[{"language": "en-US", "translation": "Coefficient of Friction"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_wear_rate_mm3_per_nm', NULL, 'input', '{"step": 1e-08, "suffix": "mm\u00b3/Nm"}', 'raw', NULL, FALSE, TRUE, 409, 'half', FALSE, '[{"language": "en-US", "translation": "Specific Wear Rate"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tribology_wear_volume_mm3', NULL, 'input', '{"step": 1e-06, "suffix": "mm\u00b3"}', 'raw', NULL, FALSE, TRUE, 410, 'half', FALSE, '[{"language": "en-US", "translation": "Wear Volume"}]', NULL, '[{"name": "show when tribology", "rule": {"_and": [{"test_type": {"_eq": "tribology"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── optical_microscopy → test_sessions (inline, shows when test_type=optical_microscopy) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'optical_microscopy_mode', NULL, 'select-dropdown', '{"choices": [{"text": "Brightfield", "value": "brightfield"}, {"text": "Darkfield", "value": "darkfield"}, {"text": "DIC", "value": "dic"}, {"text": "Polarized", "value": "polarized"}, {"text": "Phase contrast", "value": "phase_contrast"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 420, 'half', FALSE, '[{"language": "en-US", "translation": "Illumination Mode"}]', NULL, '[{"name": "show when optical_microscopy", "rule": {"_and": [{"test_type": {"_eq": "optical_microscopy"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'optical_microscopy_objective_magnification', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 421, 'half', FALSE, '[{"language": "en-US", "translation": "Objective Magnification (e.g. 50x)"}]', NULL, '[{"name": "show when optical_microscopy", "rule": {"_and": [{"test_type": {"_eq": "optical_microscopy"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'optical_microscopy_etchant', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 422, 'half', FALSE, '[{"language": "en-US", "translation": "Etchant"}]', NULL, '[{"name": "show when optical_microscopy", "rule": {"_and": [{"test_type": {"_eq": "optical_microscopy"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'optical_microscopy_etch_time_s', NULL, 'input', '{"step": 0.1, "suffix": "s"}', 'raw', NULL, FALSE, TRUE, 423, 'half', FALSE, '[{"language": "en-US", "translation": "Etch Time"}]', NULL, '[{"name": "show when optical_microscopy", "rule": {"_and": [{"test_type": {"_eq": "optical_microscopy"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'optical_microscopy_image_scale_um_per_px', NULL, 'input', '{"step": 1e-05, "suffix": "\u00b5m/px"}', 'raw', NULL, FALSE, TRUE, 424, 'half', FALSE, '[{"language": "en-US", "translation": "Image Scale"}]', NULL, '[{"name": "show when optical_microscopy", "rule": {"_and": [{"test_type": {"_eq": "optical_microscopy"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'optical_microscopy_notable_features', NULL, 'input-multiline', NULL, 'raw', NULL, FALSE, TRUE, 425, 'full', FALSE, '[{"language": "en-US", "translation": "Notable Features"}]', NULL, '[{"name": "show when optical_microscopy", "rule": {"_and": [{"test_type": {"_eq": "optical_microscopy"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── tem → test_sessions (inline, shows when test_type=tem) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tem_operating_voltage_kv', NULL, 'input', '{"step": 0.5, "suffix": "kV"}', 'raw', NULL, FALSE, TRUE, 440, 'half', FALSE, '[{"language": "en-US", "translation": "Operating Voltage"}]', NULL, '[{"name": "show when tem", "rule": {"_and": [{"test_type": {"_eq": "tem"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tem_imaging_mode', NULL, 'select-dropdown', '{"choices": [{"text": "Bright field", "value": "BF"}, {"text": "Dark field", "value": "DF"}, {"text": "HRTEM", "value": "HRTEM"}, {"text": "STEM", "value": "STEM"}, {"text": "Diffraction (SAD)", "value": "SAD"}, {"text": "EDS", "value": "EDS"}, {"text": "EELS", "value": "EELS"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 441, 'half', FALSE, '[{"language": "en-US", "translation": "Imaging Mode"}]', NULL, '[{"name": "show when tem", "rule": {"_and": [{"test_type": {"_eq": "tem"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tem_camera_length_mm', NULL, 'input', '{"step": 0.1, "suffix": "mm"}', 'raw', NULL, FALSE, TRUE, 442, 'half', FALSE, '[{"language": "en-US", "translation": "Camera Length"}]', NULL, '[{"name": "show when tem", "rule": {"_and": [{"test_type": {"_eq": "tem"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tem_specimen_prep', NULL, 'select-dropdown', '{"choices": [{"text": "FIB lift-out", "value": "fib"}, {"text": "Electropolishing", "value": "electropolish"}, {"text": "Ion milling", "value": "ion_mill"}, {"text": "Ultramicrotomy", "value": "ultramicrotome"}, {"text": "Replica", "value": "replica"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 443, 'half', FALSE, '[{"language": "en-US", "translation": "Specimen Preparation"}]', NULL, '[{"name": "show when tem", "rule": {"_and": [{"test_type": {"_eq": "tem"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tem_magnification_range', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 444, 'half', FALSE, '[{"language": "en-US", "translation": "Magnification Range"}]', NULL, '[{"name": "show when tem", "rule": {"_and": [{"test_type": {"_eq": "tem"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'tem_notable_features', NULL, 'input-multiline', NULL, 'raw', NULL, FALSE, TRUE, 445, 'full', FALSE, '[{"language": "en-US", "translation": "Notable Features"}]', NULL, '[{"name": "show when tem", "rule": {"_and": [{"test_type": {"_eq": "tem"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── alicona → test_sessions (inline, shows when test_type=alicona) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'alicona_objective_magnification', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 460, 'half', FALSE, '[{"language": "en-US", "translation": "Objective Magnification"}]', NULL, '[{"name": "show when alicona", "rule": {"_and": [{"test_type": {"_eq": "alicona"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'alicona_vertical_resolution_nm', NULL, 'input', '{"step": 0.1, "suffix": "nm"}', 'raw', NULL, FALSE, TRUE, 461, 'half', FALSE, '[{"language": "en-US", "translation": "Vertical Resolution"}]', NULL, '[{"name": "show when alicona", "rule": {"_and": [{"test_type": {"_eq": "alicona"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'alicona_lateral_resolution_um', NULL, 'input', '{"step": 0.0001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 462, 'half', FALSE, '[{"language": "en-US", "translation": "Lateral Resolution"}]', NULL, '[{"name": "show when alicona", "rule": {"_and": [{"test_type": {"_eq": "alicona"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'alicona_measured_area', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 463, 'half', FALSE, '[{"language": "en-US", "translation": "Measured Area (e.g. 2\u00d72 mm)"}]', NULL, '[{"name": "show when alicona", "rule": {"_and": [{"test_type": {"_eq": "alicona"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'alicona_sa_um', NULL, 'input', '{"step": 0.0001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 464, 'half', FALSE, '[{"language": "en-US", "translation": "Sa (areal roughness)"}]', NULL, '[{"name": "show when alicona", "rule": {"_and": [{"test_type": {"_eq": "alicona"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'alicona_sz_um', NULL, 'input', '{"step": 0.0001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 465, 'half', FALSE, '[{"language": "en-US", "translation": "Sz (max height)"}]', NULL, '[{"name": "show when alicona", "rule": {"_and": [{"test_type": {"_eq": "alicona"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── clemx → test_sessions (inline, shows when test_type=clemx) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_analysis_type', NULL, 'select-dropdown', '{"choices": [{"text": "Grain size", "value": "grain_size"}, {"text": "Phase fraction", "value": "phase_fraction"}, {"text": "Porosity", "value": "porosity"}, {"text": "Inclusion rating", "value": "inclusion"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 480, 'half', FALSE, '[{"language": "en-US", "translation": "Analysis Type"}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_objective_magnification', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 481, 'half', FALSE, '[{"language": "en-US", "translation": "Objective Magnification"}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_n_fields_analysed', NULL, 'input', '{"step": 1}', 'raw', NULL, FALSE, TRUE, 482, 'half', FALSE, '[{"language": "en-US", "translation": "# Fields Analysed"}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_etchant', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 483, 'half', FALSE, '[{"language": "en-US", "translation": "Etchant"}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_mean_grain_size_um', NULL, 'input', '{"step": 0.001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 484, 'half', FALSE, '[{"language": "en-US", "translation": "Mean Grain Size"}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_astm_grain_size_number', NULL, 'input', '{"step": 0.01}', 'raw', NULL, FALSE, TRUE, 485, 'half', FALSE, '[{"language": "en-US", "translation": "ASTM Grain Size No."}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'clemx_phase_fraction_pct', NULL, 'input', '{"step": 0.01, "suffix": "%"}', 'raw', NULL, FALSE, TRUE, 486, 'half', FALSE, '[{"language": "en-US", "translation": "Phase Fraction"}]', NULL, '[{"name": "show when clemx", "rule": {"_and": [{"test_type": {"_eq": "clemx"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── dct → test_sessions (inline, shows when test_type=dct) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dct_beam_energy_kev', NULL, 'input', '{"step": 0.1, "suffix": "keV"}', 'raw', NULL, FALSE, TRUE, 500, 'half', FALSE, '[{"language": "en-US", "translation": "Beam Energy"}]', NULL, '[{"name": "show when dct", "rule": {"_and": [{"test_type": {"_eq": "dct"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dct_voxel_size_um', NULL, 'input', '{"step": 0.0001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 501, 'half', FALSE, '[{"language": "en-US", "translation": "Voxel Size"}]', NULL, '[{"name": "show when dct", "rule": {"_and": [{"test_type": {"_eq": "dct"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dct_n_projections', NULL, 'input', '{"step": 1}', 'raw', NULL, FALSE, TRUE, 502, 'half', FALSE, '[{"language": "en-US", "translation": "# Projections"}]', NULL, '[{"name": "show when dct", "rule": {"_and": [{"test_type": {"_eq": "dct"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dct_scan_time_min', NULL, 'input', '{"step": 0.1, "suffix": "min"}', 'raw', NULL, FALSE, TRUE, 503, 'half', FALSE, '[{"language": "en-US", "translation": "Scan Time"}]', NULL, '[{"name": "show when dct", "rule": {"_and": [{"test_type": {"_eq": "dct"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dct_n_grains_indexed', NULL, 'input', '{"step": 1}', 'raw', NULL, FALSE, TRUE, 504, 'half', FALSE, '[{"language": "en-US", "translation": "# Grains Indexed"}]', NULL, '[{"name": "show when dct", "rule": {"_and": [{"test_type": {"_eq": "dct"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dct_notable_features', NULL, 'input-multiline', NULL, 'raw', NULL, FALSE, TRUE, 505, 'full', FALSE, '[{"language": "en-US", "translation": "Notable Features"}]', NULL, '[{"name": "show when dct", "rule": {"_and": [{"test_type": {"_eq": "dct"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── ct_scan → test_sessions (inline, shows when test_type=ct_scan) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_tube_voltage_kv', NULL, 'input', '{"step": 0.1, "suffix": "kV"}', 'raw', NULL, FALSE, TRUE, 520, 'half', FALSE, '[{"language": "en-US", "translation": "Tube Voltage"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_tube_current_ua', NULL, 'input', '{"step": 0.1, "suffix": "\u00b5A"}', 'raw', NULL, FALSE, TRUE, 521, 'half', FALSE, '[{"language": "en-US", "translation": "Tube Current"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_voxel_size_um', NULL, 'input', '{"step": 0.0001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 522, 'half', FALSE, '[{"language": "en-US", "translation": "Voxel Size"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_n_projections', NULL, 'input', '{"step": 1}', 'raw', NULL, FALSE, TRUE, 523, 'half', FALSE, '[{"language": "en-US", "translation": "# Projections"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_exposure_time_ms', NULL, 'input', '{"step": 0.1, "suffix": "ms"}', 'raw', NULL, FALSE, TRUE, 524, 'half', FALSE, '[{"language": "en-US", "translation": "Exposure Time"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_filter_material', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 525, 'half', FALSE, '[{"language": "en-US", "translation": "Beam Filter (e.g. 0.5 mm Cu)"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_porosity_pct', NULL, 'input', '{"step": 0.0001, "suffix": "%"}', 'raw', NULL, FALSE, TRUE, 526, 'half', FALSE, '[{"language": "en-US", "translation": "Measured Porosity"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'ct_scan_notable_features', NULL, 'input-multiline', NULL, 'raw', NULL, FALSE, TRUE, 527, 'full', FALSE, '[{"language": "en-US", "translation": "Notable Features"}]', NULL, '[{"name": "show when ct_scan", "rule": {"_and": [{"test_type": {"_eq": "ct_scan"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── fatigue → test_sessions (inline, shows when test_type=fatigue) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_loading_mode', NULL, 'select-dropdown', '{"choices": [{"text": "Axial", "value": "axial"}, {"text": "Rotating bending", "value": "rotating_bending"}, {"text": "Three-point bending", "value": "three_point_bending"}, {"text": "Torsion", "value": "torsion"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 540, 'half', FALSE, '[{"language": "en-US", "translation": "Loading Mode"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_stress_ratio_r', NULL, 'input', '{"step": 0.001}', 'raw', NULL, FALSE, TRUE, 541, 'half', FALSE, '[{"language": "en-US", "translation": "Stress Ratio (R)"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_max_stress_mpa', NULL, 'input', '{"step": 0.01, "suffix": "MPa"}', 'raw', NULL, FALSE, TRUE, 542, 'half', FALSE, '[{"language": "en-US", "translation": "Max Stress"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_stress_amplitude_mpa', NULL, 'input', '{"step": 0.01, "suffix": "MPa"}', 'raw', NULL, FALSE, TRUE, 543, 'half', FALSE, '[{"language": "en-US", "translation": "Stress Amplitude"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_frequency_hz', NULL, 'input', '{"step": 0.001, "suffix": "Hz"}', 'raw', NULL, FALSE, TRUE, 544, 'half', FALSE, '[{"language": "en-US", "translation": "Frequency"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_waveform', NULL, 'select-dropdown', '{"choices": [{"text": "Sine", "value": "sine"}, {"text": "Triangle", "value": "triangle"}, {"text": "Square", "value": "square"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 545, 'half', FALSE, '[{"language": "en-US", "translation": "Waveform"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_test_temp_celsius', NULL, 'input', '{"step": 0.1, "suffix": "\u00b0C"}', 'raw', NULL, FALSE, TRUE, 546, 'half', FALSE, '[{"language": "en-US", "translation": "Test Temperature"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_cycles_to_failure', NULL, 'input', '{"step": 1}', 'raw', NULL, FALSE, TRUE, 547, 'half', FALSE, '[{"language": "en-US", "translation": "Cycles to Failure"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'fatigue_runout', 'cast-boolean', 'toggle', NULL, 'boolean', NULL, FALSE, TRUE, 548, 'half', FALSE, '[{"language": "en-US", "translation": "Runout (no failure)?"}]', NULL, '[{"name": "show when fatigue", "rule": {"_and": [{"test_type": {"_eq": "fatigue"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── creep → test_sessions (inline, shows when test_type=creep) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_applied_stress_mpa', NULL, 'input', '{"step": 0.01, "suffix": "MPa"}', 'raw', NULL, FALSE, TRUE, 560, 'half', FALSE, '[{"language": "en-US", "translation": "Applied Stress"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_test_temp_celsius', NULL, 'input', '{"step": 0.1, "suffix": "\u00b0C"}', 'raw', NULL, FALSE, TRUE, 561, 'half', FALSE, '[{"language": "en-US", "translation": "Test Temperature"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_atmosphere', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 562, 'half', FALSE, '[{"language": "en-US", "translation": "Atmosphere"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_time_to_rupture_h', NULL, 'input', '{"step": 0.001, "suffix": "h"}', 'raw', NULL, FALSE, TRUE, 563, 'half', FALSE, '[{"language": "en-US", "translation": "Time to Rupture"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_steady_state_creep_rate_per_s', NULL, 'input', '{"step": 1e-12, "suffix": "s\u207b\u00b9"}', 'raw', NULL, FALSE, TRUE, 564, 'half', FALSE, '[{"language": "en-US", "translation": "Steady-State Creep Rate"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_rupture_elongation_pct', NULL, 'input', '{"step": 0.001, "suffix": "%"}', 'raw', NULL, FALSE, TRUE, 565, 'half', FALSE, '[{"language": "en-US", "translation": "Elongation at Rupture"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'creep_reduction_of_area_pct', NULL, 'input', '{"step": 0.001, "suffix": "%"}', 'raw', NULL, FALSE, TRUE, 566, 'half', FALSE, '[{"language": "en-US", "translation": "Reduction of Area"}]', NULL, '[{"name": "show when creep", "rule": {"_and": [{"test_type": {"_eq": "creep"}}]}, "hidden": false, "readonly": false, "required": false}]');

-- ── dma → test_sessions (inline, shows when test_type=dma) ──
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_deformation_mode', NULL, 'select-dropdown', '{"choices": [{"text": "Tension", "value": "tension"}, {"text": "Single cantilever", "value": "single_cantilever"}, {"text": "Dual cantilever", "value": "dual_cantilever"}, {"text": "Three-point bending", "value": "three_point_bending"}, {"text": "Shear", "value": "shear"}, {"text": "Compression", "value": "compression"}, {"text": "Other", "value": "other"}]}', 'raw', NULL, FALSE, TRUE, 580, 'half', FALSE, '[{"language": "en-US", "translation": "Deformation Mode"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_frequency_hz', NULL, 'input', '{"step": 0.001, "suffix": "Hz"}', 'raw', NULL, FALSE, TRUE, 581, 'half', FALSE, '[{"language": "en-US", "translation": "Frequency"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_temperature_range', NULL, 'input', NULL, 'raw', NULL, FALSE, TRUE, 582, 'half', FALSE, '[{"language": "en-US", "translation": "Temperature Range (e.g. \u221250\u2013300\u00b0C)"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_heating_rate_c_per_min', NULL, 'input', '{"step": 0.001, "suffix": "\u00b0C/min"}', 'raw', NULL, FALSE, TRUE, 583, 'half', FALSE, '[{"language": "en-US", "translation": "Heating Rate"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_amplitude_um', NULL, 'input', '{"step": 0.001, "suffix": "\u00b5m"}', 'raw', NULL, FALSE, TRUE, 584, 'half', FALSE, '[{"language": "en-US", "translation": "Displacement Amplitude"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_storage_modulus_mpa', NULL, 'input', '{"step": 0.001, "suffix": "MPa"}', 'raw', NULL, FALSE, TRUE, 585, 'half', FALSE, '[{"language": "en-US", "translation": "Storage Modulus (E'')"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_loss_modulus_mpa', NULL, 'input', '{"step": 0.001, "suffix": "MPa"}', 'raw', NULL, FALSE, TRUE, 586, 'half', FALSE, '[{"language": "en-US", "translation": "Loss Modulus (E'''')"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_tan_delta', NULL, 'input', '{"step": 1e-05}', 'raw', NULL, FALSE, TRUE, 587, 'half', FALSE, '[{"language": "en-US", "translation": "tan \u03b4"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');
INSERT INTO directus_fields (collection, field, special, interface, options, display, display_options, readonly, hidden, sort, width, required, translations, note, conditions) VALUES ('test_sessions', 'dma_glass_transition_celsius', NULL, 'input', '{"step": 0.01, "suffix": "\u00b0C"}', 'raw', NULL, FALSE, TRUE, 588, 'half', FALSE, '[{"language": "en-US", "translation": "Glass Transition (Tg)"}]', NULL, '[{"name": "show when dma", "rule": {"_and": [{"test_type": {"_eq": "dma"}}]}, "hidden": false, "readonly": false, "required": false}]');

COMMIT;

-- migrate:down
DELETE FROM directus_fields WHERE collection='test_sessions' AND (field LIKE 'tribology\_%' OR field LIKE 'optical_microscopy\_%' OR field LIKE 'tem\_%' OR field LIKE 'alicona\_%' OR field LIKE 'clemx\_%' OR field LIKE 'dct\_%' OR field LIKE 'ct_scan\_%' OR field LIKE 'fatigue\_%' OR field LIKE 'creep\_%' OR field LIKE 'dma\_%');
