-- migrate:up
-- The central entity of the system.
-- Dual identifier strategy (see docs/legacy-data-analysis.md §6):
--   sample_id  = UUID — hidden, permanent PK; all FKs point here.
--   sample_code = TEXT — human-readable pseudonym generated deterministically
--                 (e.g. 10-AA-MF-2023-06-03); unique-constrained, never the PK.
-- Self-referential genealogy captures disc→child-piece lineage.

CREATE TABLE physical_samples (
    sample_id           UUID        NOT NULL DEFAULT uuid_generate_v4(),
    sample_code         VARCHAR(64) NOT NULL,
    material_id         UUID,
    project_id          UUID,
    form                TEXT,
    mass_grams          NUMERIC(12, 4),
    diameter_mm         NUMERIC(10, 4),
    length_mm           NUMERIC(10, 4),
    thickness_mm        NUMERIC(10, 4),
    current_status      TEXT        NOT NULL DEFAULT 'active',
    manufactured_date   DATE,
    export_controlled   BOOLEAN     NOT NULL DEFAULT FALSE,
    notes               TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version             INTEGER     NOT NULL DEFAULT 1,
    CONSTRAINT physical_samples_pkey PRIMARY KEY (sample_id),
    CONSTRAINT physical_samples_code_unique UNIQUE (sample_code),
    CONSTRAINT physical_samples_material_id_fkey
        FOREIGN KEY (material_id)
        REFERENCES materials (material_id),
    CONSTRAINT physical_samples_project_id_fkey
        FOREIGN KEY (project_id)
        REFERENCES projects (project_id),
    CONSTRAINT physical_samples_status_check
        CHECK (current_status IN ('active', 'consumed', 'destroyed', 'archived'))
);

COMMENT ON TABLE physical_samples
    IS 'The central entity: every physical sample created in the lab.'
       ' sample_id is the durable hidden PK; sample_code is the human-readable label.';
COMMENT ON COLUMN physical_samples.sample_id
    IS 'UUID primary key. All foreign keys in other tables point here. Never changes.';
COMMENT ON COLUMN physical_samples.sample_code
    IS 'Human-readable pseudonym, e.g. 10-AA-MF-2023-06-03. Generated by'
       ' generate_sample_code(). Unique-constrained. NOT the primary key.';
COMMENT ON COLUMN physical_samples.form
    IS 'Physical form, e.g. disc, billet, powder-compact, coupon.';
COMMENT ON COLUMN physical_samples.mass_grams
    IS 'Current mass of the sample in grams.';
COMMENT ON COLUMN physical_samples.diameter_mm
    IS 'Outer diameter in millimetres, if applicable.';
COMMENT ON COLUMN physical_samples.length_mm
    IS 'Length in millimetres, if applicable.';
COMMENT ON COLUMN physical_samples.thickness_mm
    IS 'Thickness in millimetres, if applicable.';
COMMENT ON COLUMN physical_samples.current_status
    IS 'Lifecycle state: active | consumed | destroyed | archived.';
COMMENT ON COLUMN physical_samples.export_controlled
    IS 'TRUE if subject to ITAR/ECJU controls. May be inherited from material or project.';

-- ---------------------------------------------------------------------------
-- Self-referential genealogy.
-- A disc can be cut into many child pieces; a child may have many parent sources.
-- Mirrors the Parent / Contains / Contains_All columns in the Inventory sheet.
-- ---------------------------------------------------------------------------
CREATE TABLE sample_genealogy (
    child_sample_id     UUID        NOT NULL,
    parent_sample_id    UUID        NOT NULL,
    relationship_type   TEXT        NOT NULL DEFAULT 'derived_from',
    fraction            NUMERIC(5, 4),
    notes               TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT sample_genealogy_pkey PRIMARY KEY (child_sample_id, parent_sample_id),
    CONSTRAINT sample_genealogy_child_fkey
        FOREIGN KEY (child_sample_id)
        REFERENCES physical_samples (sample_id),
    CONSTRAINT sample_genealogy_parent_fkey
        FOREIGN KEY (parent_sample_id)
        REFERENCES physical_samples (sample_id),
    CONSTRAINT sample_genealogy_no_self_loop
        CHECK (child_sample_id <> parent_sample_id),
    CONSTRAINT sample_genealogy_relationship_check
        CHECK (relationship_type IN ('derived_from', 'cut_from', 'sintered_from', 'powder_from'))
);

COMMENT ON TABLE sample_genealogy
    IS 'Self-referential lineage: which samples were produced from which others.'
       ' Captures the Parent/Contains structure in the legacy Inventory sheet.';
COMMENT ON COLUMN sample_genealogy.relationship_type
    IS 'Nature of the derivation: derived_from, cut_from, sintered_from, powder_from.';
COMMENT ON COLUMN sample_genealogy.fraction
    IS 'Fraction of parent mass that became this child (0–1). NULL if unknown.';

-- ---------------------------------------------------------------------------
-- Material provenance: sample → raw_stock_lots (many-to-many).
-- ---------------------------------------------------------------------------
CREATE TABLE sample_stock_provenance (
    sample_id           UUID            NOT NULL,
    lot_id              UUID            NOT NULL,
    mass_used_grams     NUMERIC(12, 4),
    notes               TEXT,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    CONSTRAINT sample_stock_provenance_pkey PRIMARY KEY (sample_id, lot_id),
    CONSTRAINT sample_stock_provenance_sample_fkey
        FOREIGN KEY (sample_id)
        REFERENCES physical_samples (sample_id),
    CONSTRAINT sample_stock_provenance_lot_fkey
        FOREIGN KEY (lot_id)
        REFERENCES raw_stock_lots (lot_id)
);

COMMENT ON TABLE sample_stock_provenance
    IS 'Many-to-many: which raw_stock_lots contributed to which physical_samples.'
       ' Enables full material-provenance tracing back to inbound material receipts.';
COMMENT ON COLUMN sample_stock_provenance.mass_used_grams
    IS 'Mass of raw stock consumed to produce this sample, in grams.';

-- migrate:down

DROP TABLE IF EXISTS sample_stock_provenance CASCADE;
DROP TABLE IF EXISTS sample_genealogy CASCADE;
DROP TABLE IF EXISTS physical_samples CASCADE;
