-- migrate:up
-- Unified manufacturing operations table.
-- Replaces the separate FAST Runs and Machining Operations sheets.
-- Method-specific parameters live in recorded_metadata JSONB (keyed by
-- method_parameters.parameter_name). See ADR-0004 for the JSONB rationale.
-- See docs/experiment-sheets-and-naming.md for pass_code / force_file_id naming.

CREATE TABLE manufacturing_operations (
    operation_id            UUID        NOT NULL DEFAULT uuid_generate_v4(),
    sample_id               UUID        NOT NULL,
    method_id               UUID        NOT NULL,
    project_id              UUID,
    equipment_id            UUID,
    tool_id                 UUID,
    insert_edge_id          UUID,
    operator_name           TEXT,
    operation_sequence      INTEGER,
    pass_code               VARCHAR(128),
    operation_date          TIMESTAMPTZ,
    recorded_metadata       JSONB       NOT NULL DEFAULT '{}',
    capture_software        TEXT,
    capture_frequency_khz   NUMERIC(10, 4),
    file_storage_pointer    TEXT,
    force_file_id           TEXT,
    nc_program_text         TEXT,
    nc_program_file_uri     TEXT,
    outcome_notes           TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                 INTEGER     NOT NULL DEFAULT 1,
    CONSTRAINT manufacturing_operations_pkey PRIMARY KEY (operation_id),
    CONSTRAINT manufacturing_operations_sample_fkey
        FOREIGN KEY (sample_id)
        REFERENCES physical_samples (sample_id),
    CONSTRAINT manufacturing_operations_method_fkey
        FOREIGN KEY (method_id)
        REFERENCES manufacturing_methods (method_id),
    CONSTRAINT manufacturing_operations_project_fkey
        FOREIGN KEY (project_id)
        REFERENCES projects (project_id),
    CONSTRAINT manufacturing_operations_equipment_fkey
        FOREIGN KEY (equipment_id)
        REFERENCES equipment (equipment_id),
    CONSTRAINT manufacturing_operations_tool_fkey
        FOREIGN KEY (tool_id)
        REFERENCES tools (tool_id),
    CONSTRAINT manufacturing_operations_insert_edge_fkey
        FOREIGN KEY (insert_edge_id)
        REFERENCES insert_edges (edge_id)
);

-- GIN index on JSONB for key/value containment queries.
CREATE INDEX manufacturing_operations_metadata_gin_idx
    ON manufacturing_operations USING gin (recorded_metadata);

-- Fast lookup of all operations for a sample in chronological order.
CREATE INDEX manufacturing_operations_sample_seq_idx
    ON manufacturing_operations (sample_id, operation_sequence);

COMMENT ON TABLE manufacturing_operations
    IS 'Unified operation log for all manufacturing steps on a sample.'
       ' Replaces separate FAST Runs and Machining Operations sheets.'
       ' Method-specific fields are stored in recorded_metadata JSONB.';
COMMENT ON COLUMN manufacturing_operations.sample_id
    IS 'The sample this operation was performed on. FK to physical_samples.';
COMMENT ON COLUMN manufacturing_operations.method_id
    IS 'The manufacturing method used, e.g. FAST, Turning. FK to manufacturing_methods.';
COMMENT ON COLUMN manufacturing_operations.operation_sequence
    IS 'Ordering of this operation within the sample lifecycle (1 = first).';
COMMENT ON COLUMN manufacturing_operations.pass_code
    IS 'Human-readable pass identifier, e.g. 9-AA-MR-2023-03-23-F9.'
       ' Generated by generate_pass_code(). Not the PK.';
COMMENT ON COLUMN manufacturing_operations.recorded_metadata
    IS 'JSONB bag of method-specific parameters. Keys are defined in method_parameters.'
       ' E.g. {"peak_temperature_celsius": 1100, "atmosphere": "Argon"} for FAST.';
COMMENT ON COLUMN manufacturing_operations.capture_software
    IS 'Data-capture app and version, e.g. MATLAB ABFP 0.18. Needed to parse force files.';
COMMENT ON COLUMN manufacturing_operations.capture_frequency_khz
    IS 'Sampling frequency in kilohertz, e.g. 25.6. Needed to interpret force files.';
COMMENT ON COLUMN manufacturing_operations.file_storage_pointer
    IS 'MinIO URI of the raw data file for this operation, if one was captured.';
COMMENT ON COLUMN manufacturing_operations.force_file_id
    IS 'Human-readable force-file ID (e.g. 9-AA-MR-2023-03-23-F9-20MPM_0.05feed_0.1DoC).'
       ' Generated by generate_force_file_id(). Maps to the MinIO object key.';
COMMENT ON COLUMN manufacturing_operations.nc_program_text
    IS 'Inline NC/G-code program text for machining passes.';
COMMENT ON COLUMN manufacturing_operations.nc_program_file_uri
    IS 'MinIO URI for the G-code file if stored as an artifact.';

-- migrate:down

DROP INDEX IF EXISTS manufacturing_operations_sample_seq_idx;
DROP INDEX IF EXISTS manufacturing_operations_metadata_gin_idx;
DROP TABLE IF EXISTS manufacturing_operations CASCADE;
